// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYH4q_wjoWMGMy_M5CNik341jTR3msA70',
    appId: '1:496237149588:web:d20109f407da07434ca381',
    messagingSenderId: '496237149588',
    projectId: 'masjid-app-2adea',
    authDomain: 'masjid-app-2adea.firebaseapp.com',
    storageBucket: 'masjid-app-2adea.firebasestorage.app',
    measurementId: 'G-KHY0M47QFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbCOm1ImMSw7m9WXtUwfD7vYpbMqDYXeg',
    appId: '1:496237149588:android:f6df6a5b1a4dc9ec4ca381',
    messagingSenderId: '496237149588',
    projectId: 'masjid-app-2adea',
    storageBucket: 'masjid-app-2adea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbL-fp7q_k_KwTt9qMZrtEBhsxcai4FvE',
    appId: '1:496237149588:ios:49fc74cd222074114ca381',
    messagingSenderId: '496237149588',
    projectId: 'masjid-app-2adea',
    storageBucket: 'masjid-app-2adea.firebasestorage.app',
    iosBundleId: 'com.example.masjid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbL-fp7q_k_KwTt9qMZrtEBhsxcai4FvE',
    appId: '1:496237149588:ios:49fc74cd222074114ca381',
    messagingSenderId: '496237149588',
    projectId: 'masjid-app-2adea',
    storageBucket: 'masjid-app-2adea.firebasestorage.app',
    iosBundleId: 'com.example.masjid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYH4q_wjoWMGMy_M5CNik341jTR3msA70',
    appId: '1:496237149588:web:28a1800ef06c4b7e4ca381',
    messagingSenderId: '496237149588',
    projectId: 'masjid-app-2adea',
    authDomain: 'masjid-app-2adea.firebaseapp.com',
    storageBucket: 'masjid-app-2adea.firebasestorage.app',
    measurementId: 'G-0P3DCR73VR',
  );

}